language: php

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1

before_script:
  - composer self-update --2
  - composer install

script:
  - composer run-script phpunit
  - composer run-script phpstan

